BlogSM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Index.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name = 'signup'),
    path('login/', auth_views.LoginView.
                as_view(template_name = 'accounts/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('profile/<int:pk>', views.ProfileDetail.as_view(),
                                                    name = 'profile_detail'),
    path('profile_pic/<int:pk>/update', views.ProfileUpdate.as_view(),
                                                    name = 'profile_update')
]

accounts/models.py
from django.db import models
from django.contrib import auth
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return self.username

class Profile(models.Model):
    GENDER_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female'),
        ('n', 'Perfer not to say')
    )
    user = models.OneToOneField(auth.models.User, on_delete=models.CASCADE)
    gender = models.CharField(max_length = 1, choices = GENDER_CHOICES,
                                                                blank = True)
    birth_date = models.DateField(null = True, blank = True)
    location = models.CharField(max_length = 50, blank = True)
    profile_pic  = models.ImageField(upload_to = 'profiles_images',blank = True)
    profile_pic_thumbnail = ImageSpecField(source='profile_pic',
                                      processors=[ResizeToFill(150, 150)],
                                      format='JPEG',
                                      options={'quality': 100})
    bio = models.TextField()

    def __str__(self):
        return self.user.username + '\'s Profile'

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 256, unique = True)
    content = models.TextField()
    date_published = models.DateTimeField(default = timezone.now)
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.title + ' by ' + self.author

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile, User

class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('gender', 'birth_date', 'location', 'profile_pic', 'bio')

BlogSM/views.py
from django.views.generic import TemplateView

class Index(TemplateView):
    template_name = 'index.html'

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views.generic import CreateView, UpdateView, DetailView
from django.urls import reverse_lazy, reverse
from . import forms
from .models import Profile
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('login')

class ProfileUpdate(UpdateView):
    model = get_user_model()
    form_class = forms.ProfileUpdateForm
    template_name = 'accounts/profile_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('accounts:profile_detail', kwargs={'pk': pk})

    def get_initial(self):
        initial = super().get_initial()
        initial['gender'] = self.request.user.profile.gender
        initial['birth_date'] = self.request.user.profile.birth_date
        initial['location'] = self.request.user.profile.location
        initial['profile_pic'] = self.request.user.profile.profile_pic
        initial['bio'] = self.request.user.profile.bio
        return initial

class ProfileDetail(DetailView):
    model = get_user_model()
    template_name = 'accounts/profile_detail.html'

posts/views.py
from django.shortcuts import render
from django.views.generic import (ListView, DetailView,
                                CreateView, UpdateView, DeleteView)
from .models import Post
# Create your views here.

class PostList(ListView):
    model =  Post

class PostDetail(DetailView):
    model = Post

class PostDetail(CreateView):
    model = Post

class PostDetail(UpdateView):
    model = Post

class PostDetail(DeleteView):
    model = Post

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block content %}
<div class="container login-form">
  <h1>LogIn</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Login">
  </form>
</div>
<link rel="stylesheet" href="{% static "css/accounts/login-form.css" %}">
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <div class="container profile-box">
    <button class="btn btn-dark update-btn-profile" type="button" name="button"><a id="profile-update-anchor" href="{% url 'accounts:profile_update' pk=user.pk %}">Update Profile</a></button>
    <img class="profile-image" src="{{ user.profile.profile_pic_thumbnail.url }}" alt="{% static "images/default.jpg" %}">
    <h1 class="profile-name">{{ user.username|title }}</h1>
    <div class="container">
      <div class="row profile-info-grid">
        <div class="col-sm">
          <h3>Birth date</h3>
          <h6>{{ user.profile.birth_date|date:"d/m/Y" }}</h6>
        </div>
        <div class="col-sm mid-grid-profile">
          <h3>Gender</h3>
          <h6>{{ user.profile.gender|title }}</h6>
        </div>
        <div class="col-sm">
          <h3>Location</h3>
          <h6>{{ user.profile.location }}</h6>
        </div>
      </div>
    </div>
    <div class="container">
      <h3>BIO</h3>
      <p class="profile-bio">{{ user.profile.bio }}</p>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block content %}
<div class="container profile-box">
  <h1>Update Profile</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="Save">
  </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block content %}
<div class="container signup-form">
  <h1>SignUp</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" name="" value="SignUp">
  </form>
</div>
<link rel="stylesheet" href="{% static "css/accounts/signup-form.css" %}">
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BlogSM</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "master.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url "home" %}">BlogSM</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url "home" %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:profile_detail" pk=user.pk %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:logout" %}">Logout</a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "accounts:signup" %}">SignUp</a>
          </li>
        </ul>
        {% endif %}

      </div>
    </nav>
    {% block content %}

    {% endblock %}
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

{% endblock %}